name: SVG Validation

on:
  pull_request:
    paths:
      - '**.svg'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run JS action on SVG files
        run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.changed-files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            if [[ ${added_modified_file} == *.svg ]]; then
              node svg-check.js ${added_modified_file}
            fi
          done

      - name: Post comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const errorFile = 'errors.md';
            if (fs.existsSync(errorFile)) {
              const errors = fs.readFileSync(errorFile, 'utf8');
              const issue_number = context.issue.number;
              github.issues.createComment({
                issue_number: issue_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: errors
              });
            }
