name: SVG Validation

env:
  issue: false

on:
  pull_request:
    paths:
      - '**.svg'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Run JS action on SVG files
        run: |
          node svg-check.js $(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .svg$ | xargs)

      - name: Post comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const errorFile = 'errors.md';
            if (fs.existsSync(errorFile)) {
              const errors = fs.readFileSync(errorFile, 'utf8');
              const issue_number = context.issue.number;
              github.rest.issues.createComment({
                issue_number: issue_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: errors
              });
              console.log('::set-env name=issue::true');
            }

      - name: Add label
        uses: actions-ecosystem/action-add-labels@v1
        run: |
          if [ -f "issue.md" ]; then
            echo "::set-output name=labels::changes requested"
          else
            echo "::set-output name=labels::needs review"
    
      - name: Remove label
        uses: ctions-ecosystem/action-remove-labels@v1
        run: |
          if [ -f "issue.md" ]; then
            echo "::set-output name=labels::needs review"
          else
            echo "::set-output name=labels::changes requested"
      
      
